### ISSUE TITLE
Test the offline support

### ISSUE THREAD

**Issue by eZanmoto** [haf/openlung-website#3]
This would ideally be in the form of PWA functionality for ease-of-use.

Navigate to the site and use your Dev Toolbar to turn off internet availability. See how the site responds. Are we missing content? Images?

**Comment by haf** [comment]
Done

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/193115/77256479-e147c180-6c6e-11ea-988f-3b1946cbadef.png">
